var html = '';

html += '<dt id="h_g_menu_01kojin" class="now"><a href="/">個人のお客さま</a></dt>';
html += '<dd>';
html += '<dl class="h_g_menu">';
html += '<dt id="h_g_menu_01kojin_01" class="h_g_menu_01kojin_dt"><a href="/kojin/access/kj_acs_index.html" class="h_g_menu_01_01 js_menu_open" aria-controls="h_g_menu_acs"><span>店舗・ATM</span></a></dt>';
html += '<dd class="h_g_menu_01_01" id="h_g_menu_acs">';
html += '<dl class="h_g_menu_panel">';
html += '<dt class="h_g_menu_panel-top"><a href="/kojin/access/kj_acs_index.html"><em>店舗・ATM　トップ</em></a></dt>';
html += '<dd class="h_g_menu_panel-body">';
html += '<ul class="h_g_menu_panel-list">';
html += '<li><a href="http://map.japanpost.jp/pc/?link_id=atmMap" target="_blank"><em>店舗・ATM検索<span class="icon_link"><span class="txt_n">（別ウィンドウで開く）</span></span></em></a></li>';
html += '<li><a href="/kojin/access/kj_acs_area.html"><em>ゆうちょ銀行の直営店</em></a></li>';
html += '<li><a href="/kojin/access/atm/kj_acs_atm_goriyo.html"><em>ATMご利用時間・料金</em></a></li>';
html += '<li><a href="/kojin/access/atm/kj_acs_atm_hikidasiseigen.html"><em>ATMの引き出し制限等について</em></a></li>';
html += '<li><a href="/kojin/access/atm_cd/kj_acs_atmcd_atmcd.html"><em>ATM・CD提携金融機関のご案内</em></a></li>';
html += '<li><a href="/kojin/access/atm/kj_acs_atm_ias.html"><em>International ATM Service（海外発行カードによる現金引出しサービス）</em></a></li>';
html += '</ul>';
html += '</dd>';
html += '</dl>';
html += '<div class="h_g_menu_close"><button>閉じる</button></div>';
html += '</dd>';
html += '<dt id="h_g_menu_01kojin_02" class="h_g_menu_01kojin_dt"><a href="/kojin/chokin/kj_cho_index.html" class="h_g_menu_01_01 js_menu_open" aria-controls="h_g_menu_cho"><span>貯金</span></a></dt>';
html += '<dd class="h_g_menu_01_01" id="h_g_menu_cho">';
html += '<dl class="h_g_menu_panel">';
html += '<dt class="h_g_menu_panel-top"><a href="/kojin/chokin/kj_cho_index.html"><em>貯金　トップ</em></a></dt>';
html += '<dd class="h_g_menu_panel-body">';
html += '<ul class="h_g_menu_panel-list">';
html += '<li><a href="/kojin/chokin/tujo/kj_cho_tj_index.html"><em>通常貯金</em></a></li>';
html += '<li><a href="/kojin/chokin/chochiku/kj_cho_chk_index.html"><em>通常貯蓄貯金</em></a></li>';
html += '<li><a href="/app/app_tsucho.html"><em>ゆうちょ通帳アプリ</em></a></li>';
html += '<li><a href="/kojin/chokin/teigaku/kj_cho_tg_index.html"><em>定額貯金</em></a></li>';
html += '<li><a href="/kojin/chokin/teiki/kj_cho_tk_index.html"><em>定期貯金</em></a></li>';
html += '<li><a href="/kojin/chokin/zaikei/kj_cho_zk_index.html"><em>財産形成貯金</em></a></li>';
html += '<li><a href="/kojin/chokin/furikae/kj_cho_fe_index.html"><em>振替口座</em></a></li>';
html += '</ul>';
html += '</dd>';
html += '</dl>';
html += '<div class="h_g_menu_close"><button>閉じる</button></div>';
html += '</dd>';
html += '<dt id="h_g_menu_01kojin_03" class="h_g_menu_01kojin_dt"><a href="/kojin/sokin/kj_sk_index.html" class="h_g_menu_01_01 js_menu_open" aria-controls="h_g_menu_sk"><span>送金・支払</span></a></dt>';
html += '<dd class="h_g_menu_01_01" id="h_g_menu_sk">';
html += '<dl class="h_g_menu_panel">';
html += '<dt class="h_g_menu_panel-top"><a href="/kojin/sokin/kj_sk_index.html"><em>送金・支払　トップ</em></a></dt>';
html += '<dd class="h_g_menu_panel-body">';
html += '<ul class="h_g_menu_panel-list">';
html += '<li><a href="/kojin/sokin/koza/kj_sk_kz_index.html"><em>ゆうちょ口座への送金</em></a></li>';
html += '<li><a href="/kojin/sokin/furikomi/kj_sk_fm_furikomi.html"><em>ゆうちょ口座と他の金融機関口座間の送金</em></a></li>';
html += '<li><a href="/kojin/sokin/hikoza/kj_sk_hkz_index.html"><em>口座をもっていない相手への送金</em></a></li>';
html += '<li><a href="/kojin/sokin/sokujifurikae/kj_sk_sj_index.html"><em>即時振替サービス・双方向即時振替サービス</em></a></li>';
html += '<li><a href="/kojin/sokin/jido/kj_sk_jd_haraikomi.html"><em>自動払込み</em></a></li>';
html += '<li><a href="/kojin/sokin/kozafurikae/kj_sk_kf_furikae.html"><em>口座振替受付サービス</em></a></li>';
html += '<li><a href="/kojin/sokin/payeasy/kj_sk_pe_index.html"><em>Pay-easy(ペイジー)</em></a></li>';
html += '<li><a href="/kojin/card/kj_crd_debit.html"><em>J-Debit</em></a></li>';
html += '<li><a href="/kojin/sokin/cotra/kj_sk_cotra_index.html"><em>ことら送金</em></a></li>';
html += '<li><a href="/kojin/sokin/kokusou/kj_sk_ks_index.html"><em>国際送金</em></a></li>';
html += '</ul>';
html += '</dd>';
html += '</dl>';
html += '<div class="h_g_menu_close"><button>閉じる</button></div>';
html += '</dd>';
html += '<dt id="h_g_menu_01kojin_04" class="h_g_menu_01kojin_dt"><a href="/kojin/kyuyo_nenkin/kj_kyn_index.html" class="h_g_menu_01_01 js_menu_open" aria-controls="h_g_menu_kyn"><span>給与・<br class="sp_dis_n">年金受取り</span></a></dt>';
html += '<dd class="h_g_menu_01_01" id="h_g_menu_kyn">';
html += '<dl class="h_g_menu_panel">';
html += '<dt class="h_g_menu_panel-top"><a href="/kojin/kyuyo_nenkin/kj_kyn_index.html"><em>給与・年金受取り　トップ</em></a></dt>';
html += '<dd class="h_g_menu_panel-body">';
html += '<ul class="h_g_menu_panel-list">';
html += '<li><a href="/kojin/kyuyo_nenkin/kj_kyn_kyuyo.html"><em>給与受取</em></a></li>';
html += '<li><a href="/kojin/kyuyo_nenkin/kj_kyn_nenkin.html"><em>年金自動受取り</em></a></li>';
html += '</ul>';
html += '</dd>';
html += '</dl>';
html += '<div class="h_g_menu_close"><button>閉じる</button></div>';
html += '</dd>';
html += '<dt id="h_g_menu_01kojin_05" class="h_g_menu_01kojin_dt"><a href="/kojin/card/kj_crd_index.html" class="h_g_menu_01_01 js_menu_open" aria-controls="h_g_menu_crd"><span>キャッシュレス<br class="sp_dis_n">サービス</span></a></dt>';
html += '<dd class="h_g_menu_01_01" id="h_g_menu_crd">';
html += '<dl class="h_g_menu_panel">';
html += '<dt class="h_g_menu_panel-top"><a href="/kojin/card/kj_crd_index.html"><em>キャッシュレスサービス　トップ</em></a></dt>';
html += '<dd class="h_g_menu_panel-body">';
html += '<ul class="h_g_menu_panel-list">';
html += '<li><a href="/kojin/card/kj_crd_cashless.html"><em>ゆうちょのキャッシュレス決済</em></a></li>';
html += '<li><a href="/kojin/sokin/yuchopay/kj_sk_yp_index.html"><em>ゆうちょPay</em></a></li>';
html += '<li><a href="/kojin/card/credit/lineup/kj_crd_cdt_lu_index.html"><em>クレジットカード</em></a></li>';
html += '<li><a href="/kojin/card/rakuten/kj_crd_rak_index.html"><em>楽天カード ゆうちょ銀行デザイン</em></a></li>';
html += '<li><a href="/kojin/cashless/yuchodebit/kj_cl_yd_index.html"><em>デビットカード</em></a></li>';
html += '</ul>';
html += '</dd>';
html += '</dl>';
html += '<div class="h_g_menu_close"><button>閉じる</button></div>';
html += '</dd>';
html += '<dt id="h_g_menu_01kojin_06" class="h_g_menu_01kojin_dt"><a href="/kojin/shisanunyou/kj_suy_index.html" class="h_g_menu_01_01 js_menu_open" aria-controls="h_g_menu_suy"><span>資産運用・<br class="sp_dis_n">確定拠出年金</span></a></dt>';
html += '<dd class="h_g_menu_01_01" id="h_g_menu_suy">';
html += '<dl class="h_g_menu_panel">';
html += '<dt class="h_g_menu_panel-top"><a href="/kojin/shisanunyou/kj_suy_index.html"><em>資産運用・確定拠出年金　トップ</em></a></dt>';
html += '<dd class="h_g_menu_panel-body">';
html += '<ul class="h_g_menu_panel-list">';
html += '<li><a href="/kojin/shisanunyou/toushin/kj_suy_ts_index.html"><em>投資信託</em></a></li>';
html += '<li><a href="/kojin/shisanunyou/fundwrap/kj_suy_fw_index.html"><em>ゆうちょファンドラップ</em></a></li>';
html += '<li><a href="/kojin/shisanunyou/hengaku/kj_suy_hg_index.html"><em>変額年金保険</em></a></li>';
html += '<li><a href="/kojin/shisanunyou/kokusai/kj_suy_ks_index.html"><em>国債</em></a></li>';
html += '<li><a href="/kojin/shisanunyou/kakutei/kj_suy_kt_index.html"><em>確定拠出年金</em></a></li>';
html += '</ul>';
html += '</dd>';
html += '</dl>';
html += '<div class="h_g_menu_close"><button>閉じる</button></div>';
html += '</dd>';
html += '<dt id="h_g_menu_01kojin_07" class="h_g_menu_01kojin_dt"><a href="/kojin/loan/kj_ln_index.html" class="h_g_menu_01_01 js_menu_open" aria-controls="h_g_menu_ln"><span>ローン・貸付け</span></a></dt>';
html += '<dd class="h_g_menu_01_01" id="h_g_menu_ln">';
html += '<dl class="h_g_menu_panel">';
html += '<dt class="h_g_menu_panel-top"><a href="/kojin/loan/kj_ln_index.html"><em>ローン・貸付け　トップ</em></a></dt>';
html += '<dd class="h_g_menu_panel-body">';
html += '<ul class="h_g_menu_panel-list">';
html += '<li><a href="/kojin/loan/kj_ln_loan.html"><em>住宅ローン</em></a></li>';
html += '<li><a href="/kojin/loan/kj_ln_kasikosi.html"><em>口座貸越サービス</em></a></li>';
html += '<li><a href="/kojin/loan/kj_ln_jidou.html"><em>貯金担保自動貸付け</em></a></li>';
html += '</ul>';
html += '</dd>';
html += '</dl>';
html += '<div class="h_g_menu_close"><button>閉じる</button></div>';
html += '</dd>';
html += '<dt id="h_g_menu_01kojin_08" class="h_g_menu_01kojin_dt u_br_none"><a href="/app/app_index.html" class="h_g_menu_01_01 js_menu_open" aria-controls="h_g_menu_app"><span>アプリの<br class="sp_dis_n">ご案内</span></a></dt>';
html += '<dd class="h_g_menu_01_01" id="h_g_menu_app">';
html += '<dl class="h_g_menu_panel">';
html += '<dt class="h_g_menu_panel-top"><a href="/app/app_index.html"><em>アプリのご案内　トップ</em></a></dt>';
html += '<dd class="h_g_menu_panel-body">';
html += '<ul class="h_g_menu_panel-list">';
html += '<li><a href="/app/app_tsucho.html"><em>ゆうちょ通帳アプリ</em></a></li>';
html += '<li><a href="/app/app_ninshou.html"><em>ゆうちょ認証アプリ</em></a></li>';
html += '<li><a href="/kojin/sokin/yuchopay/kj_sk_yp_index.html"><em>ゆうちょPay</em></a></li>';
html += '<li><a href="/app/tetsuzuki/app_tz_index.html"><em>ゆうちょ手続きアプリ</em></a></li>';
html += '<li><a href="/app/app_yuchoreco.html"><em>ゆうちょレコ</em></a></li>';
html += '<li><a href="/app/app_index.html#yuchozairyu"><em>ゆうちょ在留カード読取アプリ</em></a></li>';
html += '</ul>';
html += '</dd>';
html += '</dl>';
html += '<div class="h_g_menu_close"><button>閉じる</button></div>';
html += '</dd>';
html += '</dl>';
html += '</dd>';
html += '<dt id="h_g_menu_01hojin"><a href="/hojin/hj_index.html">法人のお客さま</a></dt>';
html += '<dd class="dis_n">このページでは表示しない</dd>';
html += '<dt id="h_g_menu_01ir"><a href="/ir/ir_index.html">IR情報</a></dt>';
html += '<dd class="dis_n">このページでは表示しない</dd>';
html += '<dt id="h_g_menu_01aboutus"><a href="/aboutus/abt_index.html">企業情報</a></dt>';
html += '<dd class="dis_n">このページでは表示しない</dd>';
html += '<dt id="h_g_menu_01recruit"><a href="/recruit/rct_index.html">採用情報</a></dt>';
html += '<dd class="dis_n">このページでは表示しない</dd>';
html += '<dt id="h_g_menu_01esg"><a href="/sustainability/" target="_blank"><span>サステナビリティ</span><span class="txt_n">（別ウィンドウで開く）</span></a></dt>';
html += '<dd class="dis_n">このページでは表示しない</dd>';

var gmenu = document.getElementById('h_g_menu');
gmenu.insertAdjacentHTML('afterbegin', html);